### PR TITLE
Planner add test

### PR DESCRIPTION
**Pull request by WendyBaiYunwei**
More tests will be implemented afterwards.

### CODE REVIEW

**Comment by Creastery** [comment]
Closing this PR for the following reasons:
* You are incorporating changes in #109 here as well, which makes it unnecessarily complex for others to review this PR.
* PR #109 is not merged yet. You should rebase this branch on `master`  after that is merged .

**Comment by WendyBaiYunwei** [comment]
> Closing this PR for the following reasons:
> 
> * You are incorporating changes in #109 here as well, which makes it unnecessarily complex for others to review this PR.
> * PR #109 is not merged yet. You should rebase this branch on `master`  after that is merged .

I am creating the PR to show the graders that I wrote test. The PR will be closed after tonight's milestone check and will not be actually reviewed.

**Comment by Creastery** [comment]
> I am creating the PR to show the graders that I wrote test. The PR will be closed after tonight's milestone check and will not be actually reviewed.

Then why did you assign reviewers to this PR? You are making them do extra work!

**Comment by WendyBaiYunwei** [comment]
> > I am creating the PR to show the graders that I wrote test. The PR will be closed after tonight's milestone check and will not be actually reviewed.
> 
> Then why did you assign reviewers to this PR? You are making them do extra work!

The tag was in status.ongoing, i never set it to toReview

**Pull request closed without merging**
