### PR TITLE
docs/DeveloperGuide: update `find` command implementation details

### PR DESCRIPTION
**Pull request by lycjackie**
Let's update the Developer Guide to include details of the current
implementation and design considerations for the `find` command.

### CODE REVIEW

**Review by Letm3through — CHANGES_REQUESTED** [review]
Thanks for the update on DeveloperGuide.
Could you make few small changes in `FindCommandSequenceDiagram.png`?
I suggest:
- changing `parse(arguments)` to `parse("...")` just to be consistent with `ParseCommand("find  ...")`
- changing `:FindCommand` to `f:FindCommand` (letter `f` is just an example. Other letter is fine too) and add `f` on top of the arrows from `:FindCommandParser` to `:AddressBookParser` and from `:AddressBookParser` to `:LogicManager` in order to be consistent with other diagram and make things a bit more clear

**Comment by lycjackie** [comment]
> Thanks for the update on DeveloperGuide.
> Could you make few small changes in `FindCommandSequenceDiagram.png`?
> I suggest:
> 
> * changing `parse(arguments)` to `parse("...")` just to be consistent with `ParseCommand("find  ...")`

Alright sure will edit this.

> * changing `:FindCommand` to `f:FindCommand` (letter `f` is just an example. Other letter is fine too) and add `f` on top of the arrows from `:FindCommandParser` to `:AddressBookParser` and from `:AddressBookParser` to `:LogicManager` in order to be consistent with other diagram and make things a bit more clear

I don't think we need to letter `f` due to the code below.

https://github.com/CS2113-AY1819S2-T09-1/main/blob/7ece63a38fc21e00d508acf381fdf926ece4074c/src/main/java/seedu/address/logic/parser/AddressBookParser.java#L68-L69

https://github.com/CS2113-AY1819S2-T09-1/main/blob/7ece63a38fc21e00d508acf381fdf926ece4074c/src/main/java/seedu/address/logic/parser/FindCommandParser.java#L44

**Comment by truegitnovice** [comment]
> > Thanks for the update on DeveloperGuide.
> > Could you make few small changes in `FindCommandSequenceDiagram.png`?
> > I suggest:
> > 
> > * changing `parse(arguments)` to `parse("...")` just to be consistent with `ParseCommand("find  ...")`
> 
> Alright sure will edit this.
> 
> > * changing `:FindCommand` to `f:FindCommand` (letter `f` is just an example. Other letter is fine too) and add `f` on top of the arrows from `:FindCommandParser` to `:AddressBookParser` and from `:AddressBookParser` to `:LogicManager` in order to be consistent with other diagram and make things a bit more clear
> 
> I don't think we need to letter `f` due to the code below.
> 
> [main/src/main/java/seedu/address/logic/parser/AddressBookParser.java](https://github.com/CS2113-AY1819S2-T09-1/main/blob/7ece63a38fc21e00d508acf381fdf926ece4074c/src/main/java/seedu/address/logic/parser/AddressBookParser.java#L68-L69)
> 
> Lines 68 to 69 in [7ece63a](/CS2113-AY1819S2-T09-1/main/commit/7ece63a38fc21e00d508acf381fdf926ece4074c)
> 
>  case FindCommand.COMMAND_WORD: 
>      return new FindCommandParser().parse(arguments); 
> [main/src/main/java/seedu/address/logic/parser/FindCommandParser.java](https://github.com/CS2113-AY1819S2-T09-1/main/blob/7ece63a38fc21e00d508acf381fdf926ece4074c/src/main/java/seedu/address/logic/parser/FindCommandParser.java#L44)
> 
> Line 44 in [7ece63a](/CS2113-AY1819S2-T09-1/main/commit/7ece63a38fc21e00d508acf381fdf926ece4074c)
> 
>  return new FindCommand(predicate);

**Review by Letm3through — APPROVED** [review]
Thank you for the quick changes.
Also, thank you for adding FindCommand() on the arrow to make the context more clear.   
Reopened: Sorry for the accidental close by mispressing on the button...
Approving and merging.

**Comment by lycjackie** [comment]
> Thank you for the quick changes.
> Also, thank you for adding FindCommand() on the arrow to make the context more clear.
> Reopened: Sorry for the accidental close by mispressing on the button...
> Approving and merging.

Thanks for the quick review!

**Pull request merged**
