### PR TITLE
Logic: improve our `clear` command

### PR DESCRIPTION
**Pull request by lycjackie**
The `clear` command will always clear all data in our storage, this may
not be optimal for our users. Given that we have 3 component, namely
`modules`, `requirements` and `degree planner`. The users may prefer to
clear individual component of the storage instead.

Let's improve our `clear` command and:
* clear a parser to handle the arguments
* fix unit tests which will fails after the new implementation.

### CODE REVIEW

**Comment by Letm3through** [comment]
Since `clear` command also affects `RequirementCategory` which @chyeo is in charged, I will be tagging him as a reviewer too.

**Review by chyeo — COMMENTED** [review]
The `clear` command looks good for the `requirement` side. Will get @truegitnovice to review the `planner` part as well

**Review by Letm3through — APPROVED** [review]
LGTM. Thanks for the update.

**Review by chyeo — APPROVED** [review]
LGTM. Thanks for improving the command!

**Pull request merged**
